apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p2p3lg792-python 
  janus-idp.io/tekton: p2p3lg792-python
  backstage.io/kubernetes-id: p2p3lg792-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p2p3lg792-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  